### ISSUE TITLE
User shouldn't be able to purchase anything if it's in waitlist

### ISSUE THREAD

**Issue by HectorZR** [guillermoscript/lms-front#136]
As long as the user is in waitlist. It shouldn't be able to purchase any item from the store. Because after purchase is completed. User is redirected to dashboard.

User shouldn't have access to dashboard before waitlist approval. (IMO)

**Comment by guillermoscript** [comment]
for now im going to close this as the urls for the store and plans are not present and our target audience is not going to find it here lol
