### ISSUE TITLE
About us QA review

### ISSUE THREAD

**Issue by guillermoscript** [guillermoscript/lms-front#147]
please add a comment with all the things you find in the page @HectorZR

**Comment by HectorZR** [comment]
Typo 

![Image](https://github.com/user-attachments/assets/4aec2c06-9369-4152-8305-151f1c13ac3a)

**Comment by HectorZR** [comment]
Recomendación. Siempre hablen en plural en los textos o de manera impersonal. Hay que dar el feeling de que es un grupo grande y profesional, así sean tres pelagatos

![Image](https://github.com/user-attachments/assets/3d57ebfd-91b0-4173-817c-989e19326b53)
