### ISSUE TITLE
Move the Lesson content from the sidebar to the content of the course

### ISSUE THREAD

**Issue by guillermoscript** [guillermoscript/lms-front#8]
![Image](https://github.com/guillermoscript/lms-front/assets/52298929/cd108651-a641-4281-baf7-60aec325a814)

below the cards, we should display in a clean way the content of the course (lessons and tests)

**Comment by Enyeltov** [comment]
qlq

**Comment by guillermoscript** [comment]
![Image](https://github.com/guillermoscript/lms-front/assets/52298929/019ade9e-f9b4-4936-8052-400e1a5d92f3)
